name: Build

on: [workflow_call]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Package
      run: |
        mkdir rusty_crawler_package
        cp target/debug/rusty_crawler* rusty_crawler_package/
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: rusty_crawler_package
