name: Fail Fast

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cargo Fmt
      run: cargo fmt --check --all
    - name: Cargo Clippy
      run: cargo clippy -D warnings
