name: Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  failfast:
    uses: ./.github/workflows/failfast.yml
  build:
    uses: ./.github/workflows/build.yml
    needs: failfast
  tests:
    uses: ./.github/workflows/test.yml
    needs: build
