name: Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  failfast:
    uses: ./.github/workflows/failfast.yml
  build:
    uses: ./.github/workflows/build.yml
    needs: failfast
  tests:
    uses: ./.github/workflows/test.yml
    needs: build
  release:
    uses: ./.github/workflows/release.yml
    needs: tests
    if: ${{ (github.ref == 'refs/heads/main') && (github.event.pull_request.merged == true) }}
  testing:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "github.ref"
          echo "${{ github.ref }}"
          echo "github.event.pull_request.merged"
          echo "${{ github.event.pull_request.merged }}"
