name: Tests

on: [workflow_call]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: build
        path: target/debug
    - name: Show directory contents
      run: tree -L 3
    - name: Run tests
      run: cargo test --verbose

